### ISSUE TITLE
Add SPD tab

### ISSUE THREAD

**Issue by gamer4eg** [yutsuku/BetterCharacterStats#1]
Could you add a new tab for spells?
With the lines of each school of magic + healing.
Thank you.

**Comment by yutsuku** [comment]
Will try to look more into that as I never played any mana class this might take some time

**Comment by gamer4eg** [comment]
You need a tester mage/warlock/priest ?
Or clarify how to count the SPD?
If the second, can tell knowledgeable people.

**Comment by yutsuku** [comment]
I don't know where to look for those values or how to calculate them yet so if you have any info I would appreciate it. Testing it on mana classes will not be a problem.

**Comment by yutsuku** [comment]
Closing for now. AddOn now includes many spell related things including "Schools" tab which is spell power.
