### ISSUE TITLE
New version auras localize a problem arises.help pls

### ISSUE THREAD

**Issue by Qcat0214** [yutsuku/BetterCharacterStats#11]
hey friend.
in your new version.I need to zhCN localize auras buffs effect.But English can't make me translate exactly :(
so you can give me these auras buff name or itemID or skill name ?In that case, I can find the corresponding data in the database and translate it

**Comment by g34651684** [comment]
["Chance to hit increased by (%d)%%."] --Is it an item or a skill or a spell?
["Chance to hit reduced by (%d+)%%."] --Is it an item or a skill or a spell?
["Chance to hit decreased by (%d+)%% and %d+ Nature damage every %d+ sec."] --Is it an item or a skill or a spell?
["Lowered chance to hit."] --Is it an item or a skill or a spell?
["Increases hitpoints by 300. 15%% haste to melee attacks. 10 mana regen every 5 seconds."] --Is it an item or a skill or a spell?
["Improves your chance to hit by (%d+)%%."] --Is it an item or a skill or a spell?
["Chance for a critical hit with a spell increased by (%d+)%%."] --Is it an item or a skill or a spell?
["While active, target's critical hit chance with spells and attacks increases by 10%%."] --Is it an item or a skill or a spell?
["Increases attack power by %d+ and chance to hit by (%d+)%%."] --Is it an item or a skill or a spell?
["Holy spell critical hit chance increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Destruction spell critical hit chance increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Arcane spell critical hit chance increased by (%d+)%%.\r\nArcane spell critical hit damage increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Spell hit chance increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Increases chance for a melee, ranged, or spell critical by (%d+)%% and all attributes by %d+."] --Is it an item or a skill or a spell?
["Melee critical-hit chance reduced by (%d+)%%.\r\nSpell critical-hit chance reduced by (%d+)%%."] --Is it an item or a skill or a spell?
["Increases critical chance of spells by 10%%, melee and ranged by 5%% and grants 140 attack power. 120 minute duration."] --Is it an item or a skill or a spell?
["Holy spell critical hit chance increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Destruction spell critical hit chance increased by (%d+)%%."] --Is it an item or a skill or a spell?
["Critical strike chance with spells and melee attacks increased by (%d+)%%."] --Is it an item or a skill or a spell?

**Comment by yutsuku** [comment]
FIELD1 = SpellID
FIELD121 = Spell name
FIELD139 = Description of the spell
FIELD148 = Description of the aura (buff/debuff)

1st table used
----------------

```
select FIELD1, FIELD121, FIELD139, FIELD148 from mytable WHERE 
FIELD139 != '' 
AND FIELD148 != '' 
AND FIELD148 LIKE '%hit%'
order by field1 asc
```

<table caption="mytable (27 rows)">
  <thead>
	<tr>
	  <th class="col0">FIELD1</th>
	  <th class="col1">FIELD121</th>
	  <th class="col2">FIELD139</th>
	  <th class="col3">FIELD148</th>
	</tr>
  </thead>
  <tbody>
	<tr>
	  <td class="col0">3650</td>
	  <td class="col1">Sling Mud</td>
	  <td class="col2">Tosses mud into an enemy's eyes, reducing its chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">5514</td>
	  <td class="col1">Darken Vision</td>
	  <td class="col2">Reduces an enemy's chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">5570</td>
	  <td class="col1">Insect Swarm</td>
	  <td class="col2">The enemy target is swarmed by insects, decreasing their chance to hit by $s2% and causing $o1 Nature damage over $d.</td>
	  <td class="col3">Chance to hit decreased by $s2% and $s1 Nature damage every $t1 sec.</td>
	</tr>
	<tr>
	  <td class="col0">5884</td>
	  <td class="col1">Banshee Curse</td>
	  <td class="col2">Reduces an enemy's chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">5917</td>
	  <td class="col1">Fumble</td>
	  <td class="col2">Decreases target's chance to hit by $s1% for $d1.</td>
	  <td class="col3">Lowered chance to hit.</td>
	</tr>
	<tr>
	  <td class="col0">6530</td>
	  <td class="col1">Sling Dirt</td>
	  <td class="col2">Tosses dirt into an enemy's eyes, reducing its chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">7272</td>
	  <td class="col1">Dust Cloud</td>
	  <td class="col2">Reduces nearby enemies' chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">9612</td>
	  <td class="col1">Ink Spray</td>
	  <td class="col2">Reduces an enemy's chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">11983</td>
	  <td class="col1">Steam Jet</td>
	  <td class="col2">Inflicts $s3 Nature damage to nearby enemies, reducing their chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">16460</td>
	  <td class="col1">Festering Bites</td>
	  <td class="col2">Reduces an enemy's chance to critically hit with a melee attack by $s1%, and reduces its chance to critically hit with a spell attack by $s2%. Lasts $d.</td>
	  <td class="col3">Melee critical-hit chance reduced by $s1%.\r\nSpell critical-hit chance reduced by $s2%.</td>
	</tr>
	<tr>
	  <td class="col0">16609</td>
	  <td class="col1">Warchief's Blessing</td>
	  <td class="col2">Increases hitpoints by 300. 15% haste to melee attacks. 10 mana regen every 5 seconds.</td>
	  <td class="col3">Increases hitpoints by 300. 15% haste to melee attacks. 10 mana regen every 5 seconds.</td>
	</tr>
	<tr>
	  <td class="col0">16867</td>
	  <td class="col1">Banshee Curse</td>
	  <td class="col2">Reduces nearby enemies' chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">17105</td>
	  <td class="col1">Banshee Curse</td>
	  <td class="col2">Reduces an enemy's chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">17497</td>
	  <td class="col1">zzOLDMalown's Rally</td>
	  <td class="col2">Improves all nearby party member's chance to hit by $s1%.</td>
	  <td class="col3">Improves your chance to hit by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">17639</td>
	  <td class="col1">Wail of the Banshee</td>
	  <td class="col2">Reduces an enemy's chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">22820</td>
	  <td class="col1">Slip'kik's Savvy</td>
	  <td class="col2">Chance for a critical hit with a spell increased by $s1%.</td>
	  <td class="col3">Chance for a critical hit with a spell increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">23964</td>
	  <td class="col1">Bloodrager's Requiem</td>
	  <td class="col2">While active, target's critical hit chance with spells and attacks increases by 10%.</td>
	  <td class="col3">While active, target's critical hit chance with spells and attacks increases by 10%.</td>
	</tr>
	<tr>
	  <td class="col0">24352</td>
	  <td class="col1">Devilsaur Fury</td>
	  <td class="col2">Increases your attack power by $s1 and your chance to hit by $s2%.  Effect lasts for $d.</td>
	  <td class="col3">Increases attack power by $s1 and chance to hit by $s2%.</td>
	</tr>
	<tr>
	  <td class="col0">24498</td>
	  <td class="col1">Brilliant Light</td>
	  <td class="col2">Increases the critical hit chance of Holy spells by $s1% for $d.</td>
	  <td class="col3">Holy spell critical hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">24543</td>
	  <td class="col1">Massive Destruction</td>
	  <td class="col2">Increases the critical hit chance of your Destruction spells by $s1% for $d.</td>
	  <td class="col3">Destruction spell critical hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">24544</td>
	  <td class="col1">Arcane Potency</td>
	  <td class="col2">Increases the critical hit chance of your Arcane spells by $s1%, and increases the critical hit damage of your Arcane spells by $s2% for $d.</td>
	  <td class="col3">Arcane spell critical hit chance increased by $s1%.\r\nArcane spell critical hit damage increased by $s2%.</td>
	</tr>
	<tr>
	  <td class="col0">24610</td>
	  <td class="col1">Pagle's Broken Reel</td>
	  <td class="col2">Increases the chance to hit with spells by $s1% for $d.</td>
	  <td class="col3">Spell hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">26072</td>
	  <td class="col1">Dust Cloud</td>
	  <td class="col2">Reduces nearby enemies' chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit reduced by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">26129</td>
	  <td class="col1">Enigma's Answer</td>
	  <td class="col2">Increases Spell Hit Chance by $s1% for $d. Stacks up to 4 times.</td>
	  <td class="col3">Spell hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">27723</td>
	  <td class="col1">Dark Desire</td>
	  <td class="col2">Improves your chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">29331</td>
	  <td class="col1">Copy of Dark Desire</td>
	  <td class="col2">Improves your chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">29332</td>
	  <td class="col1">Fire-toasted Bun</td>
	  <td class="col2">Improves your chance to hit by $s1% for $d.</td>
	  <td class="col3">Chance to hit increased by $s1%.</td>
	</tr>
  </tbody>
</table>

2nd table used
----------------

```
select FIELD1, FIELD121, FIELD139, FIELD148 from mytable WHERE 
FIELD139 != '' 
AND FIELD148 != '' 
AND FIELD148 LIKE '%crit%'
order by field1 asc
```


<table caption="mytable (9 rows)">
  <thead>
	<tr>
	  <th class="col0">FIELD1</th>
	  <th class="col1">FIELD121</th>
	  <th class="col2">FIELD139</th>
	  <th class="col3">FIELD148</th>
	</tr>
  </thead>
  <tbody>
	<tr>
	  <td class="col0">15366</td>
	  <td class="col1">Songflower Serenade</td>
	  <td class="col2">Increases chance for a melee, ranged, or spell critical by $s1% and all attributes by $s2 for $d.</td>
	  <td class="col3">Increases chance for a melee, ranged, or spell critical by $s1% and all attributes by $s2.</td>
	</tr>
	<tr>
	  <td class="col0">16460</td>
	  <td class="col1">Festering Bites</td>
	  <td class="col2">Reduces an enemy's chance to critically hit with a melee attack by $s1%, and reduces its chance to critically hit with a spell attack by $s2%. Lasts $d.</td>
	  <td class="col3">Melee critical-hit chance reduced by $s1%.\r\nSpell critical-hit chance reduced by $s2%.</td>
	</tr>
	<tr>
	  <td class="col0">22820</td>
	  <td class="col1">Slip'kik's Savvy</td>
	  <td class="col2">Chance for a critical hit with a spell increased by $s1%.</td>
	  <td class="col3">Chance for a critical hit with a spell increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">22888</td>
	  <td class="col1">Rallying Cry of the Dragonslayer</td>
	  <td class="col2">Increases critical chance of spells by 10%, melee and ranged by 5% and grants 140 attack power. 120 minute duration.</td>
	  <td class="col3">Increases critical chance of spells by 10%, melee and ranged by 5% and grants 140 attack power. 120 minute duration.</td>
	</tr>
	<tr>
	  <td class="col0">23964</td>
	  <td class="col1">Bloodrager's Requiem</td>
	  <td class="col2">While active, target's critical hit chance with spells and attacks increases by 10%.</td>
	  <td class="col3">While active, target's critical hit chance with spells and attacks increases by 10%.</td>
	</tr>
	<tr>
	  <td class="col0">24498</td>
	  <td class="col1">Brilliant Light</td>
	  <td class="col2">Increases the critical hit chance of Holy spells by $s1% for $d.</td>
	  <td class="col3">Holy spell critical hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">24543</td>
	  <td class="col1">Massive Destruction</td>
	  <td class="col2">Increases the critical hit chance of your Destruction spells by $s1% for $d.</td>
	  <td class="col3">Destruction spell critical hit chance increased by $s1%.</td>
	</tr>
	<tr>
	  <td class="col0">24544</td>
	  <td class="col1">Arcane Potency</td>
	  <td class="col2">Increases the critical hit chance of your Arcane spells by $s1%, and increases the critical hit damage of your Arcane spells by $s2% for $d.</td>
	  <td class="col3">Arcane spell critical hit chance increased by $s1%.\r\nArcane spell critical hit damage increased by $s2%.</td>
	</tr>
	<tr>
	  <td class="col0">24865</td>
	  <td class="col1">Sanctified Orb</td>
	  <td class="col2">Increases your critical strike chance with spells and melee attacks by $s1%.  Lasts $d.</td>
	  <td class="col3">Critical strike chance with spells and melee attacks increased by $s1%.</td>
	</tr>
  </tbody>
</table>

**Comment by g34651684** [comment]
WoW!!!, it's amazing, Thank you very much. This is very helpful
