### ISSUE TITLE
Problems with addon, three lua error

### ISSUE THREAD

**Issue by Fanelcito** [yutsuku/BetterCharacterStats#13]
Hi, i need help because this addons dont works en Classic WoW. Those are the lua errors. 

![LUA Error 1](https://user-images.githubusercontent.com/54582189/63768702-8ac00380-c896-11e9-913a-1476bf9a9214.jpg)
![LUA Error 2](https://user-images.githubusercontent.com/54582189/63768703-8ac00380-c896-11e9-946f-132c3096787f.jpg)
![LUA Error 3](https://user-images.githubusercontent.com/54582189/63768704-8ac00380-c896-11e9-8574-7bae4d9c3fd4.jpg)

and finally that show like this... i cant see any stats.
![Addon dont works](https://user-images.githubusercontent.com/54582189/63768845-e7232300-c896-11e9-9047-f7fdf0301883.jpg)

I hope u can help me, greetings!

**Comment by yutsuku** [comment]
Sorry but all my addons aren't compatible with retail WoW versions and this will most likely not change.
