### ISSUE TITLE
Set type Statistical error

### ISSUE THREAD

**Issue by Qcat1989** [yutsuku/BetterCharacterStats#4]
Hello.
I found it in the process of using this addon about Set statistics cannot be effectively counted.
such as Paladin of Judgement Armor(5/8) effect "Set: Increases damage and healing done by magical spells and effects by up to (%d+)." cannot statistics.
Hopefully it will be fixed
Cheers!

**Comment by yutsuku** [comment]
Done. (4181196209fb72fcad696d31a87cab7ff384fcb1)
