### ISSUE TITLE
spell power not calculating correctly

### ISSUE THREAD

**Issue by trclocke** [yutsuku/BetterCharacterStats#5]
talents like priest's spiritual guidance aren't factored into spell power - i'm guessing the addon just looks for raw spell power from equipment, which isn't very useful.

**Comment by yutsuku** [comment]
Spell power is currently calculated from base stats and gear, correct.
Haven't done any work for other classes' (besides rogue) talents yet.

**Comment by trclocke** [comment]
appreciate the reply :)

since in the example of spiritual guidance spell power is added as a percentage of spirit, it's still ultimately gear based, just changes the math a bit. Looking forward to future updates!

**Comment by yutsuku** [comment]
Done (may vary by 1 point). [3e6b5008bb2425deff17acba366c804b89e4d81b]
