### ISSUE TITLE
Spell damage not included

### ISSUE THREAD

**Issue by AdamSestorp** [yutsuku/BetterCharacterStats#7]
Randomly rolled (white text) spell damage on items is not included in spell damage calculations.

**Comment by yutsuku** [comment]
Done. [0b54450b74fb49dbde6a65da5c69045b0eb815e9]

**Comment by AdamSestorp** [comment]
This kind of spell damage is not included in the calculations for spell damage in the Schools tab.

**Comment by yutsuku** [comment]
Done, this time for good I hope.
