### ISSUE TITLE
Spell crit buffs

### ISSUE THREAD

**Issue by AdamSestorp** [yutsuku/BetterCharacterStats#9]
There doesn't seem to be any support for the Rallying Cry of the Dragonslayer, Songflower or Slip'kikk's Savvy for casters at the moment (I do no know if they work for melees). Would be awesome to have these kinds of buffs included!

**Comment by yutsuku** [comment]
Most buffs/debuffs are now taken into account. [4bde4373844993b8386e28b2daf9134a0cac779d]
